#
# This is free software, license use GPLv3.
#
# Copyright (c) 2020, Chuck <fanck0605@qq.com>
#

name: openwrt-21.02

on:
  push:
    branches:
      - openwrt-21.02
  schedule:
    - cron: '00 18 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: openwrt-21.02

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo du -xh --exclude=/{proc,sys,dev} / | grep -E '^[0-9.]*?[GTPEZY]'
          sudo rm -rf /usr/local/lib/android
          sudo apt-get update
          sudo apt-get install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev quilt rsync subversion swig time xsltproc zlib1g-dev
          sudo apt-get autoremove --purge
          sudo apt-get clean
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          df -h

      - name: Build OpenWrt
        run: |
          ./build.sh

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          echo "##[set-output name=artifact_name;]OpenWrt_$(date +%Y%m%d)_NanoPi-R2S"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.assemble_artifact.outputs.artifact_name }}
          path: artifact
